# Generated by Django 5.2.7 on 2025-10-23 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payee",
            field=models.ForeignKey(
                blank=True,
                help_text="User receiving the payment (warehouse admin or rider)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
