# Generated by Django 5.2.8 on 2025-11-08 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_options_alter_order_created_at_and_more'),
        ('payments', '0003_enable_rls_payments'),
        ('riders', '0005_riderlocationhistory_ridernotification_and_more'),
        ('warehouses', '0007_alter_riderpayout_rider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance', models.FloatField(help_text='Total distance in kilometers')),
                ('rate_per_km', models.DecimalField(decimal_places=2, help_text='Rate per kilometer', max_digits=6)),
                ('computed_amount', models.DecimalField(decimal_places=2, help_text='Computed payout amount', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_status_3728e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_warehou_f69eb2_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_rider_i_f5865c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('order', 'payer')},
        ),
        migrations.AddField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('upi', 'UPI'), ('cash', 'Cash'), ('credit', 'Credit')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payee',
            field=models.ForeignKey(blank=True, help_text='Warehouse receiving the payment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payer',
            field=models.ForeignKey(help_text='Shopkeeper making the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payer'], name='payments_pa_payer_i_fc2b89_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payee'], name='payments_pa_payee_i_e6f536_idx'),
        ),
        migrations.AddField(
            model_name='payout',
            name='rider',
            field=models.ForeignKey(help_text='Rider receiving the payout', on_delete=django.db.models.deletion.CASCADE, related_name='payment_payouts', to='riders.rider'),
        ),
        migrations.AddField(
            model_name='payout',
            name='warehouse',
            field=models.ForeignKey(help_text='Warehouse processing the payout', on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='warehouses.warehouse'),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='rider',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='warehouse',
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status'], name='payments_pa_status_d49350_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['rider'], name='payments_pa_rider_i_f69b72_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['warehouse'], name='payments_pa_warehou_73ea3e_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['created_at'], name='payments_pa_created_465e24_idx'),
        ),
    ]
