# Generated by Django 5.2.8 on 2025-11-08 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeepers', '0003_enable_rls_shopkeepers'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='shopkeeper_notifications',
        ),
    ]
