# Generated by Django 5.2.7 on 2025-10-15 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="otp",
        ),
        migrations.RemoveField(
            model_name="user",
            name="otp_created_at",
        ),
    ]
