# Generated by Django 5.2.7 on 2025-10-23 06:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_shopkeeperprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopkeeperprofile",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                help_text="Geographic location (longitude, latitude)",
                null=True,
                srid=4326,
            ),
        ),
    ]
