# Generated by Django 5.2.7 on 2025-10-29
# Migration to switch from phone-based to email-based authentication

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_enable_rls_users"),
    ]

    operations = [
        # Make email field unique and required
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, db_index=True),
        ),
        # Make phone_number nullable for backward compatibility
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=20, null=True, blank=True, db_index=True),
        ),
    ]
