# Generated by Django 5.2.8 on 2026-06-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_alter_item_image_urls_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
