# Generated by Django 5.2.8 on 2026-06-10 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_item_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="image",
        ),
    ]
