# Generated by Django 5.2.7 on 2025-11-07 09:14

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0004_delete_riderprofile_rider_riders_warehou_b8597d_idx_and_more'),
        ('warehouses', '0007_alter_riderpayout_rider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated speed in km/h', max_digits=6, null=True)),
                ('is_suspicious', models.BooleanField(db_index=True, default=False, help_text='Flagged for abnormal movement')),
                ('distance_from_previous_km', models.DecimalField(blank=True, decimal_places=2, help_text='Distance from previous location in km', max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rider_location_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RiderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_assigned', 'Order Assigned'), ('order_update', 'Order Update'), ('payment', 'Payment'), ('general', 'General'), ('suspension', 'Suspension')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rider_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='rider',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('off-duty', 'Off Duty')], db_index=True, default='available', help_text='Rider availability for accepting orders', max_length=20),
        ),
        migrations.AddField(
            model_name='rider',
            name='device_identifier',
            field=models.CharField(blank=True, help_text='Unique device identifier for security', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rider',
            name='is_suspended',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether rider is suspended by admin'),
        ),
        migrations.AddField(
            model_name='rider',
            name='suspension_reason',
            field=models.TextField(blank=True, help_text='Reason for suspension', null=True),
        ),
        migrations.AddIndex(
            model_name='rider',
            index=models.Index(fields=['availability'], name='riders_availab_e67718_idx'),
        ),
        migrations.AddIndex(
            model_name='rider',
            index=models.Index(fields=['is_suspended'], name='riders_is_susp_840c63_idx'),
        ),
        migrations.AddField(
            model_name='riderlocationhistory',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='riders.rider'),
        ),
        migrations.AddField(
            model_name='ridernotification',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='riders.rider'),
        ),
        migrations.AddIndex(
            model_name='riderlocationhistory',
            index=models.Index(fields=['rider', 'timestamp'], name='rider_locat_rider_i_92b1d6_idx'),
        ),
        migrations.AddIndex(
            model_name='riderlocationhistory',
            index=models.Index(fields=['is_suspicious'], name='rider_locat_is_susp_239b1a_idx'),
        ),
        migrations.AddIndex(
            model_name='ridernotification',
            index=models.Index(fields=['rider', 'is_read'], name='rider_notif_rider_i_2c44d4_idx'),
        ),
        migrations.AddIndex(
            model_name='ridernotification',
            index=models.Index(fields=['notification_type'], name='rider_notif_notific_39cc0d_idx'),
        ),
    ]
