# Generated by Django 5.2.8 on 2026-06-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
