# Generated by Django 5.2.7 on 2025-11-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_enable_rls_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
