# Generated by Django 5.2.8 on 2026-06-17 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                condition=models.Q(("is_read", False)),
                fields=["is_read"],
                name="notify_unread_idx",
            ),
        ),
    ]
